#!/Users/leozhu/.nvm/versions/node/v10.13.0/bin/node

const process = require('process');
const { ESlint } = require('eslint');
const child_preocess = require('child_preocess');

function exec(name) {
  return new Promise((resolve, reject) => {
    child_preocess.exec(name, resolve)
  })
}

(async function main () {
  // create an instance
  const eslint = new ESlint({ fix: false })

  // lint files
  await exec('git stash push -k')

  const results = await eslint.lintFiles(['index.js'])
  
  await exec('git stash pop')

  //format the results
  const formatter = await eslint.loadFormatter('stylish')
  const resultText = formatter.format(results)

  // log
  console.log(resultText)

  for(let result of results) {
    if(result.errorCount) {
      process.exitCode = 1
    }
  }
})().catch( error => {
  process.exitCode = 1
  console.error(error)
})

console.log('hello hooks')
